scenarios = {
    "healthy": {
        "name": "Healthy Company",
        "description": "Strong compliance posture, minimal findings",
        "organization": "TechCorp Inc",
        "total_members": 52,
        "admin_count": 4,
        "inactive_accounts": [],
        "mfa_enabled_users": 52,
        "mfa_disabled_users": 0,
        "access_last_reviewed": "2026-04-20",
        "security_training_completed": 52,
        "total_training": 52,
        "expected_findings": 0,
        "risk_level": "LOW"
    },
    "needs_improvement": {
        "name": "Needs Improvement",
        "description": "Multiple findings, requires immediate attention",
        "organization": "StartupXYZ",
        "total_members": 28,
        "admin_count": 8,
        "inactive_accounts": ["contractor_old", "intern_2023", "temp_vendor"],
        "mfa_enabled_users": 22,
        "mfa_disabled_users": 6,
        "access_last_reviewed": "2026-02-15",
        "security_training_completed": 18,
        "total_training": 28,
        "expected_findings": 5,
        "risk_level": "HIGH"
    },
    "post_incident": {
        "name": "Post-Incident Recovery",
        "description": "Recovering from security incident, implementing controls",
        "organization": "FinanceHQ",
        "total_members": 95,
        "admin_count": 15,
        "inactive_accounts": ["breach_account_1", "breach_account_2", "breach_account_3"],
        "mfa_enabled_users": 85,
        "mfa_disabled_users": 10,
        "access_last_reviewed": "2026-03-01",
        "security_training_completed": 75,
        "total_training": 95,
        "expected_findings": 8,
        "risk_level": "HIGH"
    },
    "startup": {
        "name": "Early-Stage Startup",
        "description": "Basic security controls, growing infrastructure",
        "organization": "InnovateLabs",
        "total_members": 15,
        "admin_count": 5,
        "inactive_accounts": [],
        "mfa_enabled_users": 12,
        "mfa_disabled_users": 3,
        "access_last_reviewed": "2026-04-01",
        "security_training_completed": 10,
        "total_training": 15,
        "expected_findings": 3,
        "risk_level": "MEDIUM"
    },
    "enterprise": {
        "name": "Large Enterprise",
        "description": "Complex access management, multiple teams",
        "organization": "GlobalCorp",
        "total_members": 342,
        "admin_count": 28,
        "inactive_accounts": ["old_emp_1", "contractor_expired"],
        "mfa_enabled_users": 338,
        "mfa_disabled_users": 4,
        "access_last_reviewed": "2026-04-15",
        "security_training_completed": 330,
        "total_training": 342,
        "expected_findings": 2,
        "risk_level": "LOW"
    },
    "healthcare": {
        "name": "Healthcare Provider",
        "description": "HIPAA compliance focused, strict controls",
        "organization": "MediCare Systems",
        "total_members": 67,
        "admin_count": 5,
        "inactive_accounts": [],
        "mfa_enabled_users": 67,
        "mfa_disabled_users": 0,
        "access_last_reviewed": "2026-04-10",
        "security_training_completed": 67,
        "total_training": 67,
        "expected_findings": 0,
        "risk_level": "LOW"
    },
    "financial": {
        "name": "Financial Services",
        "description": "Regulatory compliance required, high security",
        "organization": "SecureBank Ltd",
        "total_members": 156,
        "admin_count": 12,
        "inactive_accounts": ["departed_emp_1"],
        "mfa_enabled_users": 155,
        "mfa_disabled_users": 1,
        "access_last_reviewed": "2026-04-18",
        "security_training_completed": 150,
        "total_training": 156,
        "expected_findings": 1,
        "risk_level": "LOW"
    },
    "non_compliant": {
        "name": "Non-Compliant Organization",
        "description": "Critical security gaps, urgent remediation needed",
        "organization": "LegacyTech Co",
        "total_members": 45,
        "admin_count": 18,
        "inactive_accounts": ["user1", "user2", "user3", "user4", "user5"],
        "mfa_enabled_users": 20,
        "mfa_disabled_users": 25,
        "access_last_reviewed": "2025-10-01",
        "security_training_completed": 15,
        "total_training": 45,
        "expected_findings": 12,
        "risk_level": "CRITICAL"
    },
    "recovering": {
        "name": "Remediation in Progress",
        "description": "Addressing previous audit findings",
        "organization": "RefreshCorp",
        "total_members": 73,
        "admin_count": 7,
        "inactive_accounts": ["old_contractor"],
        "mfa_enabled_users": 68,
        "mfa_disabled_users": 5,
        "access_last_reviewed": "2026-03-20",
        "security_training_completed": 60,
        "total_training": 73,
        "expected_findings": 4,
        "risk_level": "MEDIUM"
    },
    "perfect": {
        "name": "Perfect Compliance",
        "description": "All controls operational and effective",
        "organization": "SecureFirst Corp",
        "total_members": 89,
        "admin_count": 5,
        "inactive_accounts": [],
        "mfa_enabled_users": 89,
        "mfa_disabled_users": 0,
        "access_last_reviewed": "2026-04-22",
        "security_training_completed": 89,
        "total_training": 89,
        "expected_findings": 0,
        "risk_level": "LOW"
    }
}
